version: '3.7'

services:
  reverse-proxy:
    build:
      context: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/var/ssl/
      - ./reverse-proxy/conf.d:/etc/traefik/conf.d/
    restart: unless-stopped

  certificate-generator:
    build:
      context: certificate-generator
    volumes:
      - traefik-certificates:/var/ssl/

volumes:
  traefik-certificates:
    external: true

networks:
  default:
    external:
      name: traefik
