version: '3'

services:
  reverse-proxy:
    image: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    restart: unless-stopped

networks:
    default:
        external:
            name: traefik