debug = true
logLevel = "INFO"
defaultEntryPoints = ["http"]
keepTrailingSlash = true

[entryPoints]
  [entryPoints.http]
    address = ":80"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "localhost"
  watch = true
  exposedByDefault = false
  usebindportip = true
  network = "traefik"

[api]